# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvstore.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kvstore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rkvstore.proto\x12\x10\x63sci5105.kvstore\"D\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x16\n\x0etextbook_chunk\x18\x02 \x01(\t\x12\x11\n\tembedding\x18\x03 \x01(\x0c\"\"\n\x0bPutResponse\x12\x13\n\x0boverwritten\x18\x01 \x01(\x08\"\x19\n\x17StreamEmbeddingsRequest\"0\n\x0e\x45mbeddingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x11\n\tembedding\x18\x02 \x01(\x0c\"\x1d\n\x0eGetTextRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"8\n\x0fGetTextResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x16\n\x0etextbook_chunk\x18\x02 \x01(\t\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\"\r\n\x0bListRequest\"\x1c\n\x0cListResponse\x12\x0c\n\x04keys\x18\x01 \x03(\t\"\x0f\n\rHealthRequest\"P\n\x0eHealthResponse\x12\x13\n\x0bserver_name\x18\x01 \x01(\t\x12\x16\n\x0eserver_version\x18\x02 \x01(\t\x12\x11\n\tkey_count\x18\x03 \x01(\x04\x32\xe7\x03\n\rKeyValueStore\x12\x42\n\x03Put\x12\x1c.csci5105.kvstore.PutRequest\x1a\x1d.csci5105.kvstore.PutResponse\x12\x61\n\x10StreamEmbeddings\x12).csci5105.kvstore.StreamEmbeddingsRequest\x1a .csci5105.kvstore.EmbeddingEntry0\x01\x12N\n\x07GetText\x12 .csci5105.kvstore.GetTextRequest\x1a!.csci5105.kvstore.GetTextResponse\x12K\n\x06\x44\x65lete\x12\x1f.csci5105.kvstore.DeleteRequest\x1a .csci5105.kvstore.DeleteResponse\x12\x45\n\x04List\x12\x1d.csci5105.kvstore.ListRequest\x1a\x1e.csci5105.kvstore.ListResponse\x12K\n\x06Health\x12\x1f.csci5105.kvstore.HealthRequest\x1a .csci5105.kvstore.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kvstore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUTREQUEST']._serialized_start=35
  _globals['_PUTREQUEST']._serialized_end=103
  _globals['_PUTRESPONSE']._serialized_start=105
  _globals['_PUTRESPONSE']._serialized_end=139
  _globals['_STREAMEMBEDDINGSREQUEST']._serialized_start=141
  _globals['_STREAMEMBEDDINGSREQUEST']._serialized_end=166
  _globals['_EMBEDDINGENTRY']._serialized_start=168
  _globals['_EMBEDDINGENTRY']._serialized_end=216
  _globals['_GETTEXTREQUEST']._serialized_start=218
  _globals['_GETTEXTREQUEST']._serialized_end=247
  _globals['_GETTEXTRESPONSE']._serialized_start=249
  _globals['_GETTEXTRESPONSE']._serialized_end=305
  _globals['_DELETEREQUEST']._serialized_start=307
  _globals['_DELETEREQUEST']._serialized_end=335
  _globals['_DELETERESPONSE']._serialized_start=337
  _globals['_DELETERESPONSE']._serialized_end=370
  _globals['_LISTREQUEST']._serialized_start=372
  _globals['_LISTREQUEST']._serialized_end=385
  _globals['_LISTRESPONSE']._serialized_start=387
  _globals['_LISTRESPONSE']._serialized_end=415
  _globals['_HEALTHREQUEST']._serialized_start=417
  _globals['_HEALTHREQUEST']._serialized_end=432
  _globals['_HEALTHRESPONSE']._serialized_start=434
  _globals['_HEALTHRESPONSE']._serialized_end=514
  _globals['_KEYVALUESTORE']._serialized_start=517
  _globals['_KEYVALUESTORE']._serialized_end=1004
# @@protoc_insertion_point(module_scope)
